<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ParameterProductLink
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ParameterProductLink extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("main_product.id" => "", "parameter_value.id" => "", "linked_product.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}