<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_Author
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_Author extends Base_Admin_Controller {

  /** SearchParams. */
  protected $searchParams = array("name");

}