<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_MandrillBroadcastLink
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_MandrillBroadcastLink extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("broadcast.id" => "", "visited_recipients.id" => "");

}