<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ProductSaleCategoryProductCategory
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ProductSaleCategoryProductCategory extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("product_sale_category.id" => "", "product_category.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}