<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_UsefulTipsBroadcastPregnancyWeek
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_UsefulTipsBroadcastPregnancyWeek extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("pregnancy_week.id" => "", "useful_tips_broadcast.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}