<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_TaskSchedule
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_TaskSchedule extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("execution_type" => "", "is_active" => "");

  /** Additional Actions. Simple Array. Ex. array('view', 'print')*/
  protected $additionalItemActions = array('logs');

  /** Extra where. */
  protected $extraWhere = array('task_type' => 'periodic');


	/**
	 * @param $id
	 */
	public function logs($id) {

		if (isset($id)) {
			$this->load->helper('common/itirra_pager');
			$page = pager_get_page_number();

			$taskSchedule = ManagerHolder::get('TaskSchedule')->getById($id);
			$explodedEvent = explode('.', $taskSchedule['event']);

			$where = array('event_model' => $explodedEvent[0], 'event_method' => $explodedEvent[1]);
			ManagerHolder::get('EventLog')->setOrderBy('created_at DESC');
			$eventLogs = ManagerHolder::get('EventLog')->getAllWhereWithMyPager($where, $page, 5, 'e.*');

			$this->layout->set('eventLogs', $eventLogs->data);
			$this->layout->set('pager', $eventLogs->pager);
			$this->layout->set("hasSidebar", TRUE);
			$this->layout->set("menuItems", $this->menuItems);
			$this->layout->view('task_schedule_logs_preview');

		}
  }

}