<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ActionLimit
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ActionLimit extends Base_Admin_Controller {

  /** DateFilters. */
  protected $dateFilters = array("last_action_date");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}