<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ProductColor
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ProductColor extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("product.id" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** ImportExcludeFields. */
  protected $importExcludeFields = array("image");

  /** ExportExcludeFields. */
  protected $exportExcludeFields = array("image");

}