<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_XBroadcast
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_XBroadcast extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("template.type.id" => "", "template.id" => "", "is_single" => "");

  /** DateFilters. */
  protected $dateFilters = array("sent_date");

  /** An array of properties to rewrite creating links in list view. */
  protected $listViewLinksRewrite = array('template' => 'xbroadcasttemplate');


  /**
   * setViewParamsIndex
   * @param  $entities
   * @param  $pager
   * @param  $hasSidebar
   */
  protected function setViewParamsIndex(&$entities, &$pager, $hasSidebar) {
    $this->actions = array();
    parent::setViewParamsIndex($entities, $pager, $hasSidebar);
  }


}