<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_XBroadcastVisitedLink
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_XBroadcastVisitedLink extends Base_Admin_Controller {

  /**
   * Add edit entity.
   * @param integer $entityId
   */
  public function add_edit($entityId = null) {
    $entity = ManagerHolder::get($this->managerName)->getById($entityId, 'e.*');
    if (!$entity) {
      show_404();
    }
    redirect($entity['url']);
  }

}