<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ArticleCategory
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_tree_controller.php';
class xAdmin_ArticleCategory extends Base_Admin_Tree_Controller {

  /**
   * Implementation of PRE_SAVE event callback
   * @param Object $entity reference
   * @return Object
   */
  protected function preSave(&$entity) {
//     $entityFromDb = ManagerHolder::get($this->managerName)->getById($entity['id'], 'page_url');
//     if (!empty($entityFromDb)) {
//       if ($entityFromDb['page_url'] != $entity['page_url']) {
//         $redirectData = array('old_url' => $entityFromDb['page_url'],
//                               'new_url' => $entity['page_url']);
//         // Check if we already have a redirect from current old url or eternal cycle
//         $checkWhereArray = array(array('old_url' => $redirectData['old_url']),
//                                  array('old_url' => $redirectData['new_url'], 
//                                        'new_url' => $redirectData['old_url']));
//         foreach ($checkWhereArray as $where) {
//           $redirectUrl = ManagerHolder::get('RedirectUrl')->getOneWhere($where, 'e.*');
//           if (!empty($redirectUrl)) {
//             ManagerHolder::get('RedirectUrl')->deleteById($redirectUrl['id']);
//           }
//         }
//         ManagerHolder::get('RedirectUrl')->insert($redirectData);
//       }
//     }
  }
}