<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ProductParams
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ProductParams extends Base_Admin_Controller {

  /** SearchParams. */
  protected $searchParams = array("name");


  /**
   * Add edit process
   * @see Base_Admin_Controller::add_edit_process()
   */
  public function add_edit_process() {
    $data['name1'] = $_POST['param1'];
    $data['name2'] = $_POST['param2'];
    for ($i = 0;  $i < count($_POST['params1']); $i++) {
      $data['data'][$_POST['params1'][$i]][] = $_POST['params2'][$i]; 
    }
    $_POST['product_params'] = serialize($data);
    parent::add_edit_process();
  }

}