<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_FilterValue
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_FilterValue extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("filter.id" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Additional Actions. */
  protected $additionalActions = array('change_priority');

  /**
   * Change priority view page
  */
  public function change_priority() {

    $this->setFilter();
    $where = $this->filters;

    $roots = ManagerHolder::get($this->managerName)->getAllWhere($where, 'e.*');
    $this->layout->set('roots', $roots);
    $this->layout->set("backUrl", $this->adminBaseRoute . '/' .  strtolower($this->entityName));
    $this->layout->set("processLink", $this->adminBaseRoute . '/' .  strtolower($this->entityName) . '/change_priority_process');
    $this->layout->view('parameter_value/change_priority');
  }

  /**
   * change_priority_process
   */
  public function change_priority_process() {
    if (empty($_POST) || !isset($_POST['roots'])) show_404();
    $priority = 1;
    foreach ($_POST['roots'] as $rId) {
      ManagerHolder::get($this->entityName)->updateById($rId, 'priority', $priority);
      $priority++;
    }
    set_flash_notice('admin.messages.' . strtolower($this->entityName) . '.edit');
    redirect($this->adminBaseRoute . '/' .  strtolower($this->entityUrlName));
  }

}