<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_RedirectUrl
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_RedirectUrl extends Base_Admin_Controller {

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}