<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_Showcase
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_Showcase extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("published" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Additional Actions. Simple Array. Ex. array('view', 'print')*/
  protected $additionalItemActions = array('preview');

  /**
   * Implementation of POST_SAVE event callback
   * @param Object $entity reference
   * @return Object
   */
  protected function postSave(&$entity) {
    if(isset($_POST['products']) && !empty($_POST['products'])) {
      ManagerHolder::get('ShowcaseProduct')->deleteAllWhere(array('showcase_id' => $entity['id']));
      foreach ($_POST['products'] as $pId) {
        $data = array('showcase_id' => $entity['id'],
                      'product_id' => $pId);
        ManagerHolder::get('ShowcaseProduct')->insert($data);
      }
    }
  }

  /**
   * preview
   */
  public function preview($id) {
    $this->load->helper('project');
    $e = ManagerHolder::get($this->managerName)->getById($id, 'id');
    redirect(shop_url() . '?showcase_preview_id=' . $e['id']);
  }

}