<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_CategoryFilter
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_CategoryFilter extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("category.id" => "", "filter.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}