<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_SupplierRequest
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_SupplierRequest extends Base_Admin_Controller {

	/** Field to search in. */
	protected $searchParams = array('supplier');

	/** Date Filters. Row example: array("created_at"). */
	protected $dateFilters = array('execution_date');

	/** Additional Actions. Simple Array. Ex. array('view', 'print')*/
	protected $additionalItemActions = array('print_request', 'print_invoice', 'print_supplier_request');

	/** $savedProductParameterGroupPost */
	private $savedProductParameterGroupPost;

  /** Filters. */
  protected $filters = array("status" => "",
                             "store.id" => "");


  /**
   * Ajax add item
   */
  public function ajax_add_item() {
    if (!isset($_GET['supplierRequestId']) || empty($_GET['supplierRequestId']) || !isset($_GET['siteorderItemId']) || empty($_GET['siteorderItemId'])) {
      die('ERROR');
    }

    $supplierRequest = ManagerHolder::get('SupplierRequest')->getById($_GET['supplierRequestId'], 'e.*');
    $siteorderItem = ManagerHolder::get('SiteOrderItem')->getById($_GET['siteorderItemId'], 'e.*, siteorder.*');

    if (empty($supplierRequest) || empty($siteorderItem)) {
      die('ERROR');
    }

    $item = array();
    $item['siteorder_code'] = $siteorderItem['siteorder']['code'];
    $item['qty'] = $siteorderItem['qty'];
    $item['supplier_request_id'] = $supplierRequest['id'];
    $item['product_id'] = $siteorderItem['product_id'];
    $item['parameter_group_id'] = $siteorderItem['parameter_group_id'];
    $item['siteorder_item_id'] = $siteorderItem['id'];

    $existsItem = ManagerHolder::get('SupplierRequestProductParameterGroup')->getOneWhere(array('supplier_request_id' => $supplierRequest['id'], 'siteorder_item_id' => $siteorderItem['id']), 'e.id');

    if (!$existsItem) {
      ManagerHolder::get('SupplierRequestProductParameterGroup')->insert($item);
    } else {
      $item['id'] = $existsItem['id'];
      ManagerHolder::get('SupplierRequestProductParameterGroup')->update($item);
    }

    die('DONE');
  }

  /**
   * Ajax remove item
   */
  public function ajax_remove_item() {
    if (!isset($_GET['supplierRequestId']) || empty($_GET['supplierRequestId']) || !isset($_GET['siteorderItemId']) || empty($_GET['siteorderItemId'])) {
      die('ERROR');
    }

    ManagerHolder::get('SupplierRequestProductParameterGroup')->deleteAllWhere(array('supplier_request_id' => $_GET['supplierRequestId'], 'siteorder_item_id' => $_GET['siteorderItemId']));
    die('DONE');
  }

  /**
   * Ajax remove item
   */
  public function ajax_create() {
    if (!isset($_POST['store_id']) || empty($_POST['store_id']) || !isset($_POST['execution_date']) || empty($_POST['execution_date']) || !isset($_POST['siteorder_item_id']) || empty($_POST['siteorder_item_id'])) {
      die('ERROR');
    }

    $entity = array();
    $entity['store_id'] = $_POST['store_id'];
    $entity['execution_date'] = $_POST['execution_date'];
    $entity['id'] = ManagerHolder::get('SupplierRequest')->insert($entity);

    $siteOrderItem = ManagerHolder::get('SiteOrderItem')->getById($_POST['siteorder_item_id'], 'e.*, siteorder.*');

    $item = array();
    $item['siteorder_code'] = $siteOrderItem['siteorder']['code'];
    $item['qty'] = $siteOrderItem['qty'];
    $item['supplier_request_id'] = $entity['id'];
    $item['product_id'] = $siteOrderItem['product_id'];
    $item['parameter_group_id'] = $siteOrderItem['parameter_group_id'];
    $item['siteorder_item_id'] = $siteOrderItem['id'];

    $existsItem = ManagerHolder::get('SupplierRequestProductParameterGroup')->getOneWhere(array('supplier_request_id' => $entity['id'], 'siteorder_item_id' => $siteOrderItem['id']), 'e.id');

    if (!$existsItem) {
      ManagerHolder::get('SupplierRequestProductParameterGroup')->insert($item);
    } else {
      $item['id'] = $existsItem['id'];
      ManagerHolder::get('SupplierRequestProductParameterGroup')->update($item);
    }
    die('DONE');
  }

	/**
	 * print_invoice
	 * @param int $id
	 */
	public function print_invoice($id) {
		$request = ManagerHolder::get($this->entityName)->getById($id, 'e.*, product_parameter_group.*');
		if (empty($request)) {
			show_404();
		}

		$this->load->library('PHPExcelWrapper');
		$sheet = $this->phpexcelwrapper->getSheet();

		$sheet->getColumnDimension("A")->setWidth(24);
		$sheet->getColumnDimension("B")->setWidth(16);
		$sheet->getColumnDimension("C")->setWidth(60);
		$sheet->getColumnDimension("D")->setWidth(12);
		$sheet->getColumnDimension("E")->setWidth(14);
		$sheet->getColumnDimension("F")->setWidth(28);

		$sheet->getRowDimension(1)->setRowHeight('25');
		$sheet->getStyle('1')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
		$sheet->setCellValue("A1", 'Расходная накладная №' . $request['code'] . ' от ' . $request['execution_date']);
		$sheet->getStyle('A1')->getFont()->applyFromArray(array_merge($this->phpexcelwrapper->fontBoldStyle, array('size' => 14)));
		$sheet->mergeCells('A1:F1');
		$sheet->getStyle('A1:F1')->getBorders()->applyFromArray(array('bottom' => array('style' => PHPExcel_Style_Border::BORDER_MEDIUM,
				                                                          'color' => array('rgb' => '000000'))));

		$sheet->setCellValue("A3", 'Поставщик:');
		$sheet->mergeCells('A3:B3');
		$sheet->setCellValue("C3", 'ФОП Пода О.В.');
		$sheet->getStyle('C3')->getFont()->applyFromArray($this->phpexcelwrapper->fontBoldStyle);

		$sheet->setCellValue("C4", 'Днепр, ул. Князя Владимира Великого, 7а, оф.133');

		$sheet->setCellValue("A6", 'Получатель:');
		$sheet->mergeCells('A6:B6');
		$sheet->setCellValue("C6", 'ТОВ «Заммлер Фулфилмент», Киевская область, Броварской район, село Красиловка, проулок Дымерский 2 Тел. 0674674473');

		$rowNum = 9;

		// Product table header
		$productDataFields = array('bar_code', 'product_code', 'name', 'qty', 'price', 'note');
		for ($i=0; $i<=5; $i++) {
			$sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
			$sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER)->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
			if (isset($productDataFields[$i])) {
				$sheet->setCellValueByColumnAndRow($i, $rowNum, lang('excel.print_request.product_table.header.' . $productDataFields[$i]));
			}
		}

		$rowNum++;

		// Product table products
		$productData = array();
		if (!empty($request['product_parameter_group'])) {
			foreach ($request['product_parameter_group'] as $ppg) {
				$productData[] = array('bar_code' => !empty($ppg['parameter_group'])&&!empty($ppg['parameter_group']['bar_code'])?$ppg['parameter_group']['bar_code']:$ppg['product']['bar_code'],
									 						 'product_code'  => $ppg['product']['product_code'],
										 					 'name'  => $ppg['product']['name'] . (!empty($ppg['parameter_group'])?' ' . $ppg['parameter_group']['main_parameter_value']['name']:''),
															 'qty'   => $ppg['qty'],
															 'price' => !empty($ppg['parameter_group'])&&!empty($ppg['parameter_group']['price'])?$ppg['parameter_group']['price']:$ppg['product']['price']);
			}
		}
		if (!empty($productData)) {
			foreach ($productData as $p) {
				foreach ($p as $k => $v) {
					for ($i=0; $i<=5; $i++) {
						$sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
						$sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
						if ($i == array_search($k, $productDataFields)) {
							$sheet->setCellValueByColumnAndRow($i, $rowNum, $v);
						}
					}
				}
				$rowNum++;
			}
		}

		$this->phpexcelwrapper->flush("расходна_накладная_№" . $request['code'] . ".xls");
	}

	/**
	 * print_request
	 * @param int $id
	 */
	public function print_request($id) {
		$request = ManagerHolder::get($this->entityName)->getById($id, 'e.*, product_parameter_group.*');
		if (empty($request)) {
			show_404();
		}

		$this->load->library('PHPExcelWrapper');
		$sheet = $this->phpexcelwrapper->getSheet();

		$sheet->getColumnDimension("A")->setWidth(24);
		$sheet->getColumnDimension("B")->setWidth(16);
		$sheet->getColumnDimension("C")->setWidth(60);
		$sheet->getColumnDimension("D")->setWidth(12);
		$sheet->getColumnDimension("E")->setWidth(14);
		$sheet->getColumnDimension("F")->setWidth(28);
		$sheet->getColumnDimension("G")->setWidth(18);

		$sheet->setCellValue("A2", 'Заявка на відвантаження');
		$sheet->setCellValue("B2", $request['code']);
		$sheet->setCellValue("E2", 'Дата');
		$sheet->setCellValue("F2", $request['execution_date']);
		$sheet->setCellValue("E4", 'ТТН');
		$sheet->setCellValue("F4", $request['ttn_code']);

		$sheet->setCellValue("A4", 'Замовник (платник) - ФОП Пода О.В.');
		$sheet->mergeCells('A4:B4');

		$sheet->setCellValue("A5", 'Вантажовiдправник - ' . $request['supplier']);
		$sheet->mergeCells('A5:B5');

		$sheet->setCellValue("A6", 'Вантажоодержувач - ТОВ Zammler');
		$sheet->mergeCells('A6:B6');

		$sheet->setCellValue("A7", 'Водiй (ПОБ)');
		$sheet->mergeCells('A7:B7');

		$sheet->setCellValue("A8", 'Автомобiль (марка, держномер) - Новая почта');
		$sheet->mergeCells('A8:B8');

		$sheet->setCellValue("A9", 'Дата та час прибуття автомобiля _____ годин _____ хвилин ____ 20   р');
		$sheet->mergeCells('A9:F9');

		$sheet->setCellValue("A10", 'Пункт завантаження:');
		$sheet->getStyle('A10')->getFont()->applyFromArray($this->phpexcelwrapper->fontBoldStyle);
		$sheet->mergeCells('A10:F10');

		$sheet->setCellValue("A11", 'Пункт розвантаження: с. Красилiвка, провулок Димерський 2');
		$sheet->getStyle('A11')->getFont()->applyFromArray($this->phpexcelwrapper->fontBoldStyle);
		$sheet->mergeCells('A11:F11');

		$rowNum = 13;

		// Product table header
		$productDataFields = array('bar_code', 'product_code', 'name', 'qty', 'price', 'note', 'product_url');
		for ($i=0; $i<=6; $i++) {
			$sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
			$sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER)->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
			if (isset($productDataFields[$i])) {
				$sheet->setCellValueByColumnAndRow($i, $rowNum, lang('excel.print_request.product_table.header.' . $productDataFields[$i]));
			}
		}

		$rowNum++;

    $this->load->helper('project');

		// Product table products
		$productData = array();
		if (!empty($request['product_parameter_group'])) {
			foreach ($request['product_parameter_group'] as $ppg) {
				$productData[] = array('bar_code' => !empty($ppg['parameter_group'])&&!empty($ppg['parameter_group']['bar_code'])?$ppg['parameter_group']['bar_code']:$ppg['product']['bar_code'],
										 			 		 'product_code'  => $ppg['product']['product_code'],
															 'name'  => $ppg['product']['name'] . (!empty($ppg['parameter_group'])?' ' . $ppg['parameter_group']['main_parameter_value']['name']:''),
															 'qty'   => $ppg['qty'],
															 'price' => !empty($ppg['parameter_group'])&&!empty($ppg['parameter_group']['price'])?$ppg['parameter_group']['price']:$ppg['product']['price'],
                               'note' => !empty($ppg['siteorder_code']) ? '	№ заказа: ' . $ppg['siteorder_code'] : '',
                               'product_url' => shop_url($ppg['product']['page_url'])
                         );
			}
		}
		if (!empty($productData)) {
			foreach ($productData as $p) {
				foreach ($p as $k => $v) {
					for ($i=0; $i<=6; $i++) {
						$sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
            if ($i != 6) {
              $sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            } else {
              $sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
            }
						if ($i == array_search($k, $productDataFields)) {
							$sheet->setCellValueByColumnAndRow($i, $rowNum, $v);
						}
					}
				}
				$rowNum++;
			}
		}

		$supplier = str_replace(' ', '_', $request['supplier']);
		$this->phpexcelwrapper->flush($supplier . "_заявка_на_прием_товара_№" . $request['code'] . ".xls");
	}

  /**
   * Print supplier request
   */
	public function print_supplier_request($id) {
    $request = ManagerHolder::get($this->entityName)->getById($id, 'e.*, product_parameter_group.*');
    if (empty($request)) {
      show_404();
    }

    $this->load->library('PHPExcelWrapper');
    $sheet = $this->phpexcelwrapper->getSheet();

    $borderStyle = array('allborders' => array('style' => PHPExcel_Style_Border::BORDER_MEDIUM,
      'color' => array('rgb' => '000000')));

    $fontStyle = array('name' => 'Times New Roman', 'size' => 11);
    $fontBoldStyle = array_merge($fontStyle, array('bold' => true));

    $sheet->setTitle('Заявка Поставщику');

    $sheet->getColumnDimension("B")->setWidth(20);
    $sheet->getColumnDimension("D")->setWidth(30);
    $sheet->getColumnDimension("E")->setWidth(13);

    $sheet->setCellValue("A1", 'Заказ от MammyClub НА СКЛАД');
    $sheet->getStyle('A1')->getFont()->applyFromArray($fontBoldStyle);
    $sheet->mergeCells('A1:F1');
    $sheet->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

    $sheet->setCellValue("B3", 'Получатель:');
    $sheet->getStyle('B3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->getStyle('B3')->getFont()->applyFromArray($fontBoldStyle);

    $sheet->setCellValue("B4", 'ФИО');
    $sheet->getStyle('B4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->setCellValue("C4", 'ТОВ "Заммлер Фуллфілмент", представник');
    $sheet->getStyle('C4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B5", 'Телефон');
    $sheet->getStyle('B5')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->setCellValue("C5", '067 4674473');
    $sheet->getStyle('C5')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B6", 'Город');
    $sheet->getStyle('B6')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->setCellValue("C6", 'с. Красилівка (Броварьский р-н)');
    $sheet->getStyle('C6')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B7", 'Адресная доставка');
    $sheet->getStyle('B7')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->setCellValue("C7", 'провулок Димерський, 2');
    $sheet->getStyle('C7')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B9", 'Оплата доставки:');
    $sheet->getStyle('B9')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->getStyle('B9')->getFont()->applyFromArray($fontBoldStyle);

    $sheet->setCellValue("B10", 'Оплата доставки за счет получателя');
    $sheet->getStyle('B10')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B11", 'ОБЯЗАТЕЛЬНО указываете форму оплаты за доставку - БЕЗГОТІВКОВА');
    $sheet->getStyle('B11')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);


    $sheet->setCellValue("B13", 'Наложенный платеж');
    $sheet->getStyle('B13')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
    $sheet->getStyle('B13')->getFont()->applyFromArray($fontBoldStyle);

    $sheet->setCellValue("B14", 'БЕЗ наложенного платежа ');
    $sheet->getStyle('B14')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $sheet->setCellValue("B15", '(мы рассчитываемся с вами за товар по безналичному расчету)');
    $sheet->getStyle('B15')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

    $rowNum = 17;

    // Product table header
    $productDataFields = array('index', 'bar_code', 'product_code', 'name', 'qty');
    for ($i=0; $i<5; $i++) {
      $sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
      $sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER)->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
      if (isset($productDataFields[$i])) {
        $sheet->setCellValueByColumnAndRow($i, $rowNum, lang('excel.shipment.product_table.header.' . $productDataFields[$i]));
      }
    }

    $rowNum++;

    // Product table products
    $productData = array();
    if (!empty($request['product_parameter_group'])) {
      foreach ($request['product_parameter_group'] as $i => $ppg) {
        $productData[] = array(
          'index' => $i+1,
          'bar_code' => !empty($ppg['parameter_group'])&&!empty($ppg['parameter_group']['bar_code'])?$ppg['parameter_group']['bar_code'] . ' ':$ppg['product']['bar_code'] . ' ',
          'product_code'  => $ppg['product']['product_code'],
          'name'  => $ppg['product']['name'] . (!empty($ppg['parameter_group'])?' ' . $ppg['parameter_group']['main_parameter_value']['name']:''),
          'qty'   => $ppg['qty'],
        );
      }
    }
    if (!empty($productData)) {
      foreach ($productData as $p) {
        foreach ($p as $k => $v) {
          for ($i=0; $i<5; $i++) {
            $sheet->getStyleByColumnAndRow($i, $rowNum)->getBorders()->applyFromArray($this->phpexcelwrapper->borderStyle);
            $sheet->getStyleByColumnAndRow($i, $rowNum)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            if ($i == array_search($k, $productDataFields)) {
              $sheet->setCellValueByColumnAndRow($i, $rowNum, $v);
            }
          }
        }
        $rowNum++;
      }
    }

    $supplier = str_replace(' ', '_', $request['supplier']);
    $this->phpexcelwrapper->flush("MammyClub_НА_СКЛАД_№" . $request['code'] . "_" . $supplier . ".xls");
  }

	/**
	 * ajax_get_product_select_values
	 * @param int $brandId
	 */
	public function ajax_get_product_select_values($brandId = null) {
		if (!empty($brandId)) {
			$result = ManagerHolder::get('Product')->getAllWhere(array('brand_id' => $brandId), 'id, name');
			die(json_encode($result));
		}
		die(null);
	}

	/**
	 * ajax_get_param_groups_select_values
	 * @param int $brandId
	 */
	public function ajax_get_param_groups_select_values($productId = null) {
		if (!empty($productId)) {
			$result = ManagerHolder::get('ParameterGroup')->getAllWhere(array('product_id' => $productId), 'id, main_parameter_value.*');
			if (!empty($result)) {
				die(json_encode($result));
			}
		}
		die(null);
	}

  /**
   * Change status
   */
	public function change_status() {
    if (!isset($_GET['vl']) || !isset($_GET['supplierRequestId'])) {
      die('ERROR1');
    }
    $supplierRequestId = $_GET['supplierRequestId'];
    $status = $_GET['vl'];

    $supplierRequest = ManagerHolder::get('SupplierRequest')->getById($supplierRequestId, 'e.*');
    if (empty($supplierRequest)) {
      die('ERROR2');
    }

    if ($supplierRequest['status'] != $status) {
      ManagerHolder::get('SupplierRequest')->updateById($supplierRequestId, 'status', $status);
    }

    die('DONE');
  }

  /**
   * Change ttn
   */
	public function change_ttn() {
    if (!isset($_GET['vl']) || !isset($_GET['supplierRequestId'])) {
      die('ERROR1');
    }
    $supplierRequestId = $_GET['supplierRequestId'];
    $ttn = trim($_GET['vl']);

    $supplierRequest = ManagerHolder::get('SupplierRequest')->getById($supplierRequestId, 'e.*');
    if (empty($supplierRequest)) {
      die('ERROR2');
    }

    if ($supplierRequest['ttn_code'] != $ttn) {
      ManagerHolder::get('SupplierRequest')->updateById($supplierRequestId, 'ttn_code', $ttn);
    }

    die('DONE');
  }

  /**
   * SetAddEditDataAndShowView.
   * Set all needed view data and show add_edit form.
   * @param object $entity
   */
  protected function setAddEditDataAndShowView($entity) {
    $this->fields['file'] = array('type'=> 'file');

    parent::setAddEditDataAndShowView($entity);
  }


	/**
	 * CreateEntityPOST.
	 * Prepares POST.
	 * Creates Entity From Post.
	 * Validates Entity.
	 * @return Object
	 */
	protected function createEntityPOST() {
		$this->savedProductParameterGroupPost = isset($_POST['product_parameter_group'])?$_POST['product_parameter_group']:null;

    if(isset($_FILES['file']) && !empty($_FILES['file']) && !empty($_FILES['file']['tmp_name'])) {
      require_once('./lib/phpExcel/PHPExcel.php');
      require_once('./lib/phpExcel/PHPExcel/IOFactory.php');

      $xls = @PHPExcel_IOFactory::load($_FILES['file']['tmp_name']);

      $barCodeColumn = NULL;
      $qtyColumn = NULL;
      $products = array();

      foreach ($xls->getWorksheetIterator() as $worksheet) {
        foreach ($worksheet->getRowIterator() as $row) {
          $cellIterator = $row->getCellIterator();
          $cellIterator->setIterateOnlyExistingCells(TRUE); // Loop all cells, even if it is not set

          $product = array();
          foreach ($cellIterator as $cell) {
            if (!is_null($cell)) {
              $column = $cell->getColumn();
              $value = $cell->getValue();

              if ($barCodeColumn === NULL || $qtyColumn === NULL) {
                if ($value == 'Внешний ID') {
                  $barCodeColumn = $column;
                }
                if ($value == 'Количество') {
                  $qtyColumn = $column;
                }
              } else {
                if ($column == $barCodeColumn) {
                  $product['bar_code'] = $value;
                }
                if ($column == $qtyColumn) {
                  $product['qty'] = $value;
                }
              }
            }
          }

          if ($barCodeColumn === NULL || $qtyColumn === NULL) {
            set_flash_error('В файле отсутсвует обязательная колонока (Внешний ID, Количество)');
            redirect_to_referral();
          }
          if (!empty($product)) {
            $products[] = $product;
          }
        }
      }

      foreach ($products as $row) {
        $group = ManagerHolder::get('ParameterGroup')->getOneWhere(array('bar_code' => $row['bar_code']), 'e.*');
        $data = array();
        if (!empty($group)) {
          $data = array('parameter_group' => $group['id'], 'product' => $group['product_id'], 'qty' => $row['qty']);
        } else {
          $product = ManagerHolder::get('Product')->getOneWhere(array('bar_code' => $row['bar_code']), 'e.*');
          if (!empty($product)) {
            $data = array('product' => $product['id'], 'qty' => $row['qty']);
          }
        }

        $isNew = TRUE;
        foreach ($this->savedProductParameterGroupPost as $k => $sp) {
          if (!empty($sp['cart_item_id'])) {
            continue;
          }
          if (isset($data['parameter_group']) && $sp['parameter_group'] == $data['parameter_group'] && $sp['product'] == $data['product']) {
            $this->savedProductParameterGroupPost[$k]['qty'] += $data['qty'];
            $isNew = FALSE;
          } elseif (!isset($data['parameter_group']) && $sp['product'] == $data['product']) {
            $this->savedProductParameterGroupPost[$k]['qty'] += $data['qty'];
            $isNew = FALSE;
          }
          if (!$isNew) {
            break;
          }
        }

        if ($isNew) {
          $this->savedProductParameterGroupPost[] = $data;
        }
      }

    }

		unset($_POST['product_parameter_group']);
		return parent::createEntityPOST();
	}

	/**
	 * Implementation of POST_SAVE event callback
	 * @param Object $entity reference
	 * @return Object
	 */
	protected function postSave(&$entity) {
		ManagerHolder::get('SupplierRequestProductParameterGroup')->deleteAllWhere(array('supplier_request_id' => $entity['id']));
	  if (!empty($this->savedProductParameterGroupPost)) {
	  	foreach ($this->savedProductParameterGroupPost as $ppg) {
	  		if (isset($ppg['product']) && !empty($ppg['product'])) {
	  			$data = array('supplier_request_id' => $entity['id'],
	  				          	'product_id' =>$ppg ['product'],
	  					          'qty' => $ppg['qty'],
                        'siteorder_code' => $ppg['siteorder_code'],
                        'cart_item_id' => !empty($ppg['cart_item_id']) ? $ppg['cart_item_id'] : NULL
          );
	  			if (isset($ppg['parameter_group']) && !empty($ppg['parameter_group'])) {
	  				$data['parameter_group_id'] = $ppg['parameter_group'];
	  			}
	  			ManagerHolder::get('SupplierRequestProductParameterGroup')->insert($data);
	  		}
	  	}
	  }
	}

  /**
   * preProcessFields
   * the method is called before passing
   * fields to the layout
   */
  protected function preProcessFields(&$entity) {
    parent::preProcessFields($entity);
    $this->fields['product_parameter_group']['brand_options'] = ManagerHolder::get('ProductBrand')->getAsViewArray();
  }

  /**
   * CreateEntityId.
   * Creates Entity By Id;
   * @param integer $entityId
   * @return Object
   */
  protected function createEntityId($entityId = null) {
  	$entity = parent::createEntityId($entityId);
  	if (!empty($entity) && !empty($entity['product_parameter_group'])) {
  		$ids = get_array_vals_by_second_key($entity['product_parameter_group'], 'product_id');
  		$productIdsBrandIds = ManagerHolder::get('Product')->getAsViewArray(array(), 'brand_id', null, array('id' => $ids));
  		foreach ($entity['product_parameter_group'] as $k => $v) {
  			$entity['product_parameter_group'][$k]['brand_id'] = $productIdsBrandIds[$v['product_id']];
  			$entity['product_parameter_group'][$k]['product_options'] = ManagerHolder::get('Product')->getAsViewArray(array(), 'name', null, array('brand_id' => $productIdsBrandIds[$v['product_id']]));
  			$paramGroups = ManagerHolder::get('ParameterGroup')->getAllWhere(array('product_id' => $v['product_id']), 'id, main_parameter_value.*');
  		  if (!empty($paramGroups)) {
  		  	$options = array();
  		  	foreach ($paramGroups as $g) {
  		  		$options[$g['id']] = $g['main_parameter_value']['name'];
  		  	}
  		  	$entity['product_parameter_group'][$k]['param_group_options'] = $options;
  		  }
  		}
  	}
  	if (empty($entityId)) {
  	  unset($this->fields['code']);
  	}
  	return $entity;
  }


}