<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ArticleExample
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ArticleExample extends Base_Admin_Controller {

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Import. */
  protected $import = FALSE;

  /** Export. */
  protected $export = FALSE;

  /** ImportExcludeFields. */
  protected $importExcludeFields = array("image");

  /** ExportExcludeFields. */
  protected $exportExcludeFields = array("image");




}