<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_CounterpartyContactPerson
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_CounterpartyContactPerson extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("counterparty.id" => "", "counterparty.newpostacccount.id" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Additional Actions. */
  protected $additionalActions = array('sync');


  /**
   * setViewParamsIndex
   * @param  $entities
   * @param  $pager
   * @param  $hasSidebar
   */
  protected function setViewParamsIndex(&$entities, &$pager, $hasSidebar) {
    unset($this->actions['add'], $this->actions['delete'], $this->actions['edit']);

    foreach ($entities as &$e) {
      $e['newpostacccount.name'] = $e['counterparty']['newpostacccount']['name'];
    }

    parent::setViewParamsIndex($entities, $pager, $hasSidebar);
  }

  /**
   * Sync
   */
  public function sync() {

	  ManagerHolder::get('CounterpartyContactPerson')->sync();

    set_flash_notice('Синхронизированно');
    redirect_to_referral();
  }

}