<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_CounterpartyAddress
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_CounterpartyAddress extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("city.id" => "", "counterparty.id" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Additional Actions. */
  protected $additionalActions = array('sync');

  /**
   * setViewParamsIndex
   * @param  $entities
   * @param  $pager
   * @param  $hasSidebar
   */
  protected function setViewParamsIndex(&$entities, &$pager, $hasSidebar) {
    unset($this->actions['add'], $this->actions['delete'], $this->actions['edit']);
    parent::setViewParamsIndex($entities, $pager, $hasSidebar);
  }

  /**
   * Sync
   */
  public function sync() {

	  ManagerHolder::get('CounterpartyAddress')->sync();

    set_flash_notice('Синхронизированно');
    redirect_to_referral();
  }


}