<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ProductComment
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ProductComment extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("product.id" => "", "user.id" => "");

  /** DateFilters. */
  protected $dateFilters = array("date");

  /** Additional Actions. Simple Array. Ex. array('view', 'print')*/
  protected $additionalItemActions = array('view');

  /**
   * setViewParamsIndex
   * @param  $entities
   * @param  $pager
   * @param  $hasSidebar
   */
  protected function setViewParamsIndex(&$entities, &$pager, $hasSidebar) {
    unset($this->actions['delete']);
    parent::setViewParamsIndex($entities, $pager, $hasSidebar);
  }

  /**
   * SetAddEditDataAndShowView.
   * Set all needed view data and show add_edit form.
   * @param object $entity
   */
  protected function setAddEditDataAndShowView($entity) {
    unset($this->actions['delete']);
    parent::setAddEditDataAndShowView($entity);
  }

  /**
   * view.
   */
  public function view($id) {
    $comment = ManagerHolder::get('ProductComment')->getById($id, 'e.*, product.*');
    redirect(shop_url($comment['product']['page_url'] . '#commentid_' . $comment['id']));
  }

}