<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_PregnancyReview
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_PregnancyReview extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("user.id" => "");

}