<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_PageItemClick
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_PageItemClick extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("page_visit.id" => "");

  /** DateFilters. */
  protected $dateFilters = array("created_at");

  /** SearchParams. */
  protected $searchParams = array("name");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}