<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_SmsTemplate
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_SmsTemplate extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("is_default" => "");

  /** SearchParams. */
  protected $searchParams = array("name");

}