<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_AdminNotificationTemplate
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_AdminNotificationTemplate extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("admins.id" => "");

  /** SearchParams. */
  protected $searchParams = array("name");





}