<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_SiteOrderItem
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_SiteOrderItem extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("siteorder.id" => "", 
                             "product.id" => "", 
                             "parameter_group.id" => "", 
                             "sale.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;


  /**
   * Delete.
   * @param integer $entityId
   */
  public function delete($entityId) {
    $entity = $this->deleteFromDb($entityId);
  }

  /**
   * DeleteFromDb.
   * Deletes entity from DB and its images.
   * @param integer $entityId
   * @return Object (the deleted entity)
   */
  protected function deleteFromDb($entityId) {
    $entity = ManagerHolder::get($this->managerName)->getById($entityId);
    $this->preDelete($entityId);
    $this->addAdminLogRecord($entity, 'delete');
    ManagerHolder::get($this->managerName)->deleteById($entityId);

    $this->postDelete($entityId);
    return $entity;
  }

  /**
   * Implementation of PRE_DELETE event callback
   * @param int $entityId id
   * @return Object
   */
  protected function preDelete($entityId) {
    $siteOrderItem = ManagerHolder::get('SiteOrderItem')->getById($entityId);
    $siteOrder = $siteOrderItem['siteorder'];
    $newCartTotal = $siteOrder['total'] - $siteOrderItem['item_total'];

	  // Get new delivery price if total changed
	  $delivery = ManagerHolder::get('Delivery')->getDeliveryOfOrderAmount($newCartTotal);
	  // Update $siteOrder 'delivery_id', 'delivery_price'
	  $siteOrder = ManagerHolder::get('SiteOrder')->updateSiteOrderDeliveryType($siteOrder, $delivery);

	  ManagerHolder::get('SiteOrder')->updateById($siteOrder['id'], 'total', $newCartTotal);

    if (!empty($siteOrder['total_discount'])) {
      $totalWithDiscount = $newCartTotal - $siteOrder['total_discount'];
      $totalWithDiscount += $delivery['price'];
      ManagerHolder::get('SiteOrder')->updateById($siteOrder['id'], 'total_with_discount', $totalWithDiscount);
    } else {
    	$newCartTotal += $delivery['price'];
      ManagerHolder::get('SiteOrder')->updateById($siteOrder['id'], 'total_with_discount', $newCartTotal);
    }
  }

}