<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ExternalSourceResponseLog
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ExternalSourceResponseLog extends Base_Admin_Controller {

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}