<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_UsefulTipsBroadcastProductBoys
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_UsefulTipsBroadcastProductBoys extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("useful_tips_broadcast.id" => "", "product.id" => "");

  /** Import. */
  protected $import = TRUE;

  /** Export. */
  protected $export = TRUE;




}