<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * xAdmin_ShopComment
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'controllers/admin/base/base_admin_controller.php';
class xAdmin_ShopComment extends Base_Admin_Controller {

  /** Filters. */
  protected $filters = array("user.id" => "");

  /** DateFilters. */
  protected $dateFilters = array("date");

  /**
   * setViewParamsIndex
   * @param  $entities
   * @param  $pager
   * @param  $hasSidebar
   */
  protected function setViewParamsIndex(&$entities, &$pager, $hasSidebar) {
    unset($this->actions['delete']);
    parent::setViewParamsIndex($entities, $pager, $hasSidebar);
  }

  /**
   * SetAddEditDataAndShowView.
   * Set all needed view data and show add_edit form.
   * @param object $entity
   */
  protected function setAddEditDataAndShowView($entity) {
    unset($this->actions['delete']);
    parent::setAddEditDataAndShowView($entity);
  }

}