<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ActionLimitManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ActionLimitManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("action" => array("type" => "varchar", "class" => "required"),
                         "value_field" => array("type" => "varchar", "class" => "required"),
                         "action_count" => array("type" => "input_integer"),
                         "last_action_date" => array("type" => "datetime"));

  /** List params. */
  public $listParams = array("action_count", "last_action_date");

}