<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * AdminNotificationTemplateAdminManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class AdminNotificationTemplateAdminManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("admin_notification_template" => array("type" => "select", "relation" => array("entity_name" => "AdminNotificationTemplate")),
                         "admin" => array("type" => "select", "relation" => array("entity_name" => "Admin")));

  /** List params. */
  public $listParams = array("admin_notification_template.name", "admin.name");

}