<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * AgeOfChildManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class AgeOfChildManager extends BaseManager {

  /** Name field. */
  protected $nameField = "number";


  /** Fields. */
  public $fields = array("number" => array("type" => "input_integer", "class" => "required"));

  /** List params. */
  public $listParams = array("number");

}