<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ArticleFormManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ArticleFormManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("article_id", "form_id");


  /** Fields. */
  public $fields = array("article" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Article")),
                         "form" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Form")));

  /** List params. */
  public $listParams = array("article.name", "form.name");

}