<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ArticleCommentManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/BaseCommentManager.php';
class ArticleCommentManager extends BaseCommentManager {

  /** Name field. */
  protected $nameField = "id";
  
  /** Order by */
  protected $orderBy = "sortorder ASC";

  /** Fields. */
  public $fields = array("content" => array("type" => "tinymce", "class" => "required", "attrs" => array("maxlength" => 65536)),
                         "date" => array("type" => "datetime", "class" => "required"),
                         "published" => array("type" => "checkbox"),
                         "article" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Article")),
                         "user" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "User")));

  /** List params. */
  public $listParams = array("content", array("user" => "name"), array("article" => "name"), "date");
  
  /**
   * PreProcessWhereQuery.
   * OVERRIDE THIS METHOD IN A SUBCLASS TO ADD joins and other stuff.
   * @param Doctrine_Query $query
   * @return Doctrine_Query
   */
  protected function preProcessWhereQuery($query, $pref, $what = '*') {
    $query = parent::preProcessWhereQuery($query, $pref, $what);
    if (strpos($what, 'user.') !== FALSE || $what == '*') {
      $query->addSelect("user_img.*")->leftJoin("user.image user_img");
    }
  
    return $query;
  }

}