<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ArticleManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ArticleManager extends BaseManager {

  /** Order by */
  protected $orderBy = "priority DESC, date DESC";

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "page_url" => array("type" => "input", "class" => "required readonly", "attrs" => array("startwith" => "/статья/", "depends" => "article_name", "readonly" => "readonly", "maxlength" => 255, "translit_ignore")),
                         "content" => array("type" => "tinymce", "class" => "required", "attrs" => array("maxlength" => 65536)),
                         "category" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ArticleCategory")),
                         "author" => array("type" => "select", "relation" => array("entity_name" => "Author")),
                         "image" => array("type" => "image"),
                         "published" => array("type" => "checkbox"),
                         "hide_contents" => array("type" => "checkbox"),
                         "priority" => array("type" => "input_integer"),
                         "date" => array("type" => "date", "class" => "required"),
                         "head_section_code" => array("type" => "textarea", "class" => "charCounter"),
                         "header.title" => array("type" => "input", "class" => "required charCounter", "attrs" => array("depends" => "article_name", "maxlength" => 65536)),
                         "header.description" => array("type" => "textarea", "class" => "charCounter"));

  /** List params. */
  public $listParams = array("name", array("category" => "name"), array("author" => "name"), "comment_count", "view_count", "published", "date", "last_update", "priority");

  /**
   * Returns array of relative site urls and other info of all entities to be used in stiemap.xml
   * @return array of arrays for entities: loc, lastmod, changefreq, priority. Only loc is mandatory.
   * @example 'loc'=>'item/1', 'lastmod'=>'1990-01-21', 'changefreq'=>'daily', 'priority'=>0.5
   * @see http://www.sitemaps.org/ru/protocol.html#xmlTagDefinitions
   */
  public function getAllForSitemap() {
    $articles = $this->getAllWhere(array('published' => TRUE));

    $urls = array(array('loc' => surround_with_slashes(URL_PREFIX_ARTICLE_LIST)));
    if (!empty($articles)) {
      foreach ($articles as $a) {
        if(empty($a['name'])) {
          continue;
        }
        $urls[] = array('loc' => $a['page_url']);
      }
    }

    return $urls;
  }

}