<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * CategoryFilterManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class CategoryFilterManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("category" => array("type" => "select", "relation" => array("entity_name" => "ProductCategory")),
                         "filter" => array("type" => "select", "relation" => array("entity_name" => "Filter")));

  /** List params. */
  public $listParams = array("category.name", "filter.name");

}