<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * CountryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class CountryManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "code" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "countries" => array("type" => "multipleselect", "relation" => array("entity_name" => "RecommendedProductsBroadcast", "search" => TRUE)));

  /** List params. */
  public $listParams = array("name", array("countries" => "name"));

}