<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * CounterpartyManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class CounterpartyManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "ref" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 50)),
                         "default_sender_id" =>  array("type" => "select", "relation" => array("entity_name" => "CounterpartyContactPerson")),
                         "city" => array("type" => "select", "relation" => array("entity_name" => "City")));

  /** List params. */
  public $listParams = array("name", "city.name", "property", "newpostacccount.name");


  /**
	 * Sync
	 */
	public function sync() {
    ini_set('error_reporting', E_ALL);
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);

    $newPostAccounts = ManagerHolder::get('NewPostAccount')->getAsViewArray(array(),'api_key');
    $CI = &get_instance();
    $CI->load->library('NewPostSdk');
    foreach ($newPostAccounts as $acocuntId => $acocuntApiKey) {

      $CI->newpostsdk->setApiKey($acocuntApiKey);

      $counterparties = $CI->newpostsdk->getCounterparties();

      foreach ($counterparties as $counterparty) {
        $entity = array();
        $entity['name'] = $counterparty->Description;
        $entity['property'] = 'Sender';
        $entity['new_post_account_id'] = $acocuntId;

        $city = ManagerHolder::get('City')->getOneWhere(array('ref' => $counterparty->City), 'e.*');
        if (!empty($city)) {
          $entity['city_id'] = $city['id'];
        }

        $exists = ManagerHolder::get('Counterparty')->existsWhere(array('ref' => $counterparty->Ref));
        if ($exists) {
          ManagerHolder::get('Counterparty')->updateAllWhere(array('ref' => $counterparty->Ref), $entity);
        } else {
          $entity['ref'] = $counterparty->Ref;
          ManagerHolder::get('Counterparty')->insert($entity);
        }
      }


      $counterparties = $CI->newpostsdk->getCounterparties("Recipient");

      foreach ($counterparties as $counterparty) {
        $entity = array();
        $entity['name'] = $counterparty->Description;
        $entity['property'] = 'Recipient';
        $entity['new_post_account_id'] = $acocuntId;

        $city = ManagerHolder::get('City')->getOneWhere(array('ref' => $counterparty->City), 'e.*');
        if (!empty($city)) {
          $entity['city_id'] = $city['id'];
        }

        $exists = ManagerHolder::get('Counterparty')->existsWhere(array('ref' => $counterparty->Ref));
        if ($exists) {
          ManagerHolder::get('Counterparty')->updateAllWhere(array('ref' => $counterparty->Ref), $entity);
        } else {
          $entity['ref'] = $counterparty->Ref;
          ManagerHolder::get('Counterparty')->insert($entity);
        }
      }
    }
	}


}