<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * DeliveryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class DeliveryManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "order_price_from" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "order_price_to" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
	                       "price" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "is_active" => array("type" => "checkbox"));

  /** List params. */
  public $listParams = array("name", "is_active");


	/**
	 * Get order amount price and return delivery ID
	 * @param $orderAmount string
	 * @return array
	 */
	public function getDeliveryOfOrderAmount($orderAmount) {
		// Get delivery type of cart total amount
		$whereDelivery = array(
			'order_price_from <=' => $orderAmount,
			'order_price_to >=' => $orderAmount,
			'is_active' => 1,
		);
		$delivery = ManagerHolder::get('Delivery')->getOneWhere($whereDelivery, 'e.*');

		return $delivery;
  }

}