<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ExternalSourceResponseLogManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ExternalSourceResponseLogManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("source" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "method" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "response" => array("type" => "tinymce", "class" => "required", "attrs" => array("maxlength" => 65536)),
                         "created_at" => array("type" => "date", "class" => "required"));

  /** List params. */
  public $listParams = array("created_at");


	/**
	 * @param $model
	 * @param $data
	 */
	public function trackingNpResponse($model, $data) {
		if ($data) {
			$insert = array(
				'source' => 'NewPost',
				'method' => 'DocumentTracking',
				'model' => $model,
				'response' => json_encode($data),
				'created_at' => date(DOCTRINE_DATE_FORMAT)
			);

			ManagerHolder::get('ExternalSourceResponseLog')->insert($insert);
		}
	}

}