<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * FilterValueManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class FilterValueManager extends BaseManager {

  /** Order By. */
  protected $orderBy = 'priority ASC';

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "filter" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Filter")));

  /** List params. */
  public $listParams = array("name", "priority", array("filter" => "name"));

}