<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * FirstYearBroadcastProductManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class FirstYearBroadcastProductManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("first_year_broadcast_id" => array("type" => "input_integer", "class" => "required"),
                         "product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")));

  /** List params. */
  public $listParams = array("first_year_broadcast_id", "product.name");

}