<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * MandrillBroadcastLinkManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class MandrillBroadcastLinkManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("url" => array("type" => "textarea", "class" => "charCounter", "attrs" => array("maxlength" => 1000)),
                         "broadcast" => array("type" => "select", "relation" => array("entity_name" => "MandrillBroadcast")),
                         "visited_recipients" => array("type" => "multipleselect", "relation" => array("entity_name" => "MandrillBroadcastRecipient", "search" => TRUE)));

  /** List params. */
  public $listParams = array("broadcast.name", array("visited_recipients" => "name"));

}