<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * MandrillBroadcastVisitedLinkManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class MandrillBroadcastVisitedLinkManager extends BaseManager {

  /** Order by */
  protected $orderBy = "created_at DESC";

  /** Fields. */
  public $fields = array("recipient" => array("type" => "select", "relation" => array("entity_name" => "MandrillBroadcastRecipient")),
                         "link" => array("type" => "select", "relation" => array("entity_name" => "MandrillBroadcastLink")),
                         "created_at" => array("type" => "datetime", "class" => "readonly", "attrs" => array("disabled" => "disabled")));

  /** List params. */
  public $listParams = array("recipient.email", "broadcast.subject", "link.url", "created_at");

}