<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * PageManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class PageManager extends BaseManager {

  /** Order By. */
  protected $orderBy = 'name ASC';

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "page_url" => array("type" => "input", "class" => "required readonly", "attrs" => array("startwith" => "/", "translit_ignore" => TRUE, "depends" => "page_name", "readonly" => "readonly", "maxlength" => 255)),
                         "header.title" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255, "depends" => "page_name")),
                         "header.description" => array("type" => "textarea", "class" => "charCounter", "attrs" => array("maxlength" => 160)));

  /** List params. */
  public $listParams = array("name", "page_url");

}