<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ParameterProductLinkManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ParameterProductLinkManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("main_product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")),
                         "parameter_value" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ParameterValue")),
                         "linked_product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")));

  /** List params. */
  public $listParams = array("main_product.name", "parameter_value.name", "linked_product.name");

}