<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ParameterGroupValueInManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ParameterGroupValueInManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("parameter_group_id", "parameter_value_id");


  /** Fields. */
  public $fields = array("parameter_group" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ParameterGroup")),
                         "parameter_value" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ParameterValue")));

  /** List params. */
  public $listParams = array("parameter_group.name", "parameter_value.name");

}