<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ParameterProductManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ParameterProductManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")),
                         "parameter_main" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Parameter")),
                         "parameter_secondary" => array("type" => "select", "relation" => array("entity_name" => "Parameter")),
                         "possible_parameter_values" => array("type" => "multipleselect", "relation" => array("entity_name" => "ParameterValue", "search" => TRUE)));

  /** List params. */
  public $listParams = array("product.name", "parameter_main.name", "parameter_secondary.name", array("possible_parameter_values" => "name"));

}