<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ParameterValueProductManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ParameterValueProductManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("parameter_value_id", "product_id");


  /** Fields. */
  public $fields = array("parameter_value" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ParameterValue")),
                         "product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")));

  /** List params. */
  public $listParams = array("parameter_value.name", "product.name");

}