<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * PregnancySaleManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class PregnancySaleManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("pregnancyweek" => array("type" => "select", "relation" => array("entity_name" => "PregnancyWeek")),
                         "sale" => array("type" => "select", "relation" => array("entity_name" => "Sale")));

  /** List params. */
  public $listParams = array("pregnancyweek.name", "sale.name");

}