<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductBroadcastPregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductBroadcastPregnancyWeekManager extends BaseManager {

  /** Fields. */
  public $fields = array("pregnancy_week" => array("type" => "select", "relation" => array("entity_name" => "PregnancyWeek")),
                         "product_broadcast" => array("type" => "select", "relation" => array("entity_name" => "ProductBroadcast")));

  /** List params. */
  public $listParams = array("pregnancy_week.name", "product_broadcast.name");

}