<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductParamsManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductParamsManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "product_params" => array("type" => "include", "path" => '/includes/admin/product_params'));

  /** List params. */
  public $listParams = array("name");

}