<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductCategoryProductCategoryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductCategoryProductCategoryManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("product_category" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ProductCategory")),
                         "product_ref_category" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ProductCategory")));

  /** List params. */
  public $listParams = array("product_category.name", "product_ref_category.name");

}