<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductBroadcastCountryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductBroadcastCountryManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("country_id", "product_broadcast_id");


  /** Fields. */
  public $fields = array("country" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Country")),
                         "product_broadcast" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "ProductBroadcast")));

  /** List params. */
  public $listParams = array("country.name", "product_broadcast.name");

}