<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductBrandManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductBrandManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "page_url" => array("type" => "input", "class" => "required readonly", "attrs" => array("startwith" => "/", "depends" => "productbrand_name", "readonly" => "readonly", "maxlength" => 255, "translit_ignore" => TRUE)),
                         "description" => array("type" => "tinymce", "class" => "charCounter", "attrs" => array("maxlength" => 3000)),
                         "delivery_time" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "image" => array("type" => "image"));

  /** List params. */
  public $listParams = array("name");

}