<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductSaleManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductSaleManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("product" => array("type" => "select", "relation" => array("entity_name" => "Product")),
                         "sale" => array("type" => "select", "relation" => array("entity_name" => "Sale")),
                         "new_price" => array("type" => "input_double"));

  /** List params. */
  public $listParams = array("product.name", "sale.name", "new_price");

}