<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductImageManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductImageManager extends BaseManager {

  /** Order by */
  protected $orderBy = "priority DESC";

  /** Fields. */
  public $fields = array("product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")),
                         "image" => array("type" => "image", "class" => "required"),
                         "priority" => array("type" => "input_integer"));

  /** List params. */
  public $listParams = array("product.name", "priority");

}