<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ProductCategoryProductBrandManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ProductCategoryProductBrandManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("product_category" => array("type" => "select", "relation" => array("entity_name" => "ProductCategory")),
                         "product_brand" => array("type" => "select", "relation" => array("entity_name" => "ProductBrand")),
                         "title" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "description" => array("type" => "tinymce", "attrs" => array("maxlength" => 65536)),
                         "header_title" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "header_description" => array("type" => "textarea", "attrs" => array("maxlength" => 65536)));

  /** List params. */
  public $listParams = array("product_category.name", "product_brand.name");

}