<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * RecommendedProductsBroadcastCountryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class RecommendedProductsBroadcastCountryManager extends BaseManager {

  /** Fields. */
  public $fields = array("countries" => array("type" => "select", "relation" => array("entity_name" => "Country")),
                         "recommended_products_broadcast" => array("type" => "select", "relation" => array("entity_name" => "RecommendedProductsBroadcast")));

  /** List params. */
  public $listParams = array("countries.name", "recommended_products_broadcast.name");

}