<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * RecommendedProductsBroadcastPregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class RecommendedProductsBroadcastPregnancyWeekManager extends BaseManager {

  /** Fields. */
  public $fields = array("pregnancy_week" => array("type" => "select", "relation" => array("entity_name" => "PregnancyWeek")),
                         "recommended_products_broadcast" => array("type" => "select", "relation" => array("entity_name" => "RecommendedProductsBroadcast")));

  /** List params. */
  public $listParams = array("pregnancy_week.name", "recommended_products_broadcast.name");

}