<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * ShowcasePregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ShowcasePregnancyWeekManager extends BaseManager {

  /** Fields. */
  public $fields = array("pregnancy_week" => array("type" => "select", "relation" => array("entity_name" => "PregnancyWeek")),
                         "showcase" => array("type" => "select", "relation" => array("entity_name" => "Showcase")));

  /** List params. */
  public $listParams = array("pregnancy_week.name", "showcase.name");

}