<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * SiteOrderStatusManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class SiteOrderStatusManager extends BaseManager {

  /** Order by */
  protected $orderBy = "priority DESC";

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "k" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "is_cancel_reserve_status" => array("type" => "checkbox"),
                         "priority" => array("type" => "input_integer"),
//                         "alert_after_hour" => array("type" => "input_integer"),
                         "alert_str_time" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "admin_notification_template" => array("type" => "select", "relation" => array("entity_name" => "AdminNotificationTemplate")),
                         "published" => array("type" => "checkbox"));

  /** List params. */
  public $listParams = array("name", "k", "published", "is_cancel_reserve_status");

  /**
   * getIDByKey
   * @param string $key
   * @return integer
   */
  public function getIDByKey($key) {
    $id = null;
    $entity = $this->getOneWhere(array('k' => $key), 'e.*');
    if (!empty($entity)) {
      $id = $entity['id'];
    }
    return $id;
  }

}