<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * SmsTemplateManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class SmsTemplateManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "is_default" => array("type" => "checkbox"),
                         "text" => array("type" => "textarea", "class" => "charCounter", "attrs" => array("maxlength" => 1000)),
                         "type" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "type" => array("type" => "select", "options" => array("payment" => "Платежные реквизиты", "ttn" => "Отправка ТТН"), "class" => "required"));
  /** List params. */
  public $listParams = array("name", "is_default", "type");

}