<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * StoreProductBrandManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class StoreProductBrandManager extends BaseManager {

  /** Name field. */
  protected $nameField = "id";


  /** Fields. */
  public $fields = array("store" => array("type" => "select", "relation" => array("entity_name" => "Store")),
                         "product_brand" => array("type" => "select", "relation" => array("entity_name" => "ProductBrand")));

  /** List params. */
  public $listParams = array("store.name", "product_brand.name");

}