<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * TeamManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class TeamManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "place" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "description" => array("type" => "textarea", "class" => "charCounter", "attrs" => array("maxlength" => 1000)),
                         "image" => array("type" => "image"));

  /** List params. */
  public $listParams = array("name", "place");

}