<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UsefulTipsBroadcastUserManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UsefulTipsBroadcastUserManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("user_id", "useful_tips_broadcast_id");


  /** Fields. */
  public $fields = array("user" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "User")),
                         "useful_tips_broadcast" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "UsefulTipsBroadcast")));

  /** List params. */
  public $listParams = array("user.name", "useful_tips_broadcast.name");

}