<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UsefulTipsBroadcastPregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UsefulTipsBroadcastPregnancyWeekManager extends BaseManager {

  /** Fields. */
  public $fields = array("pregnancy_week" => array("type" => "select", "relation" => array("entity_name" => "PregnancyWeek")),
                         "useful_tips_broadcast" => array("type" => "select", "relation" => array("entity_name" => "UsefulTipsBroadcast")));

  /** List params. */
  public $listParams = array("pregnancy_week.name", "useful_tips_broadcast.name");

}