<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UsefulTipsBroadcastCountryManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UsefulTipsBroadcastCountryManager extends BaseManager {

  /** Fields. */
  public $fields = array("countries" => array("type" => "select", "relation" => array("entity_name" => "Country")),
                         "useful_tips_broadcast" => array("type" => "select", "relation" => array("entity_name" => "UsefulTipsBroadcast")));

  /** List params. */
  public $listParams = array("countries.name", "useful_tips_broadcast.name");

}