<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UsefulTipsBroadcastManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UsefulTipsBroadcastManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "attrs" => array("maxlength" => 255)),
      "subject" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
      "email_appeal" => array("type" => "tinymce", "attrs" => array("maxlength" => 255)),
      "email_intro" => array("type" => "tinymce", "class" => "charCounter", "attrs" => array("maxlength" => 5000)),
      "email_main_text" => array("type" => "tinymce", "attrs" => array("maxlength" => 65536)),
      "email_short_text" => array("type" => "tinymce", "class" => "charCounter", "attrs" => array("maxlength" => 5000)),
      "email_outro" => array("type" => "tinymce", "class" => "charCounter", "attrs" => array("maxlength" => 5000)),
      "age_of_child" => array("type" => "input"),
      "pregnancy_weeks" => array("type" => "multipleselect_chosen", "relation" => array("entity_name" => "PregnancyWeek", "search" => TRUE)),
      "sent_datetime" => array("type" => "datetime"),
      "is_sent" => array("type" => "checkbox"),
      "update_frequency" => array("type" => "select", "options" => array("0" => "0", "1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5")),
      "article" => array("type" => "select", "relation" => array("entity_name" => "Article")),
      "countries" => array("type" => "multipleselect_chosen", "relation" => array("entity_name" => "Country", "search" => TRUE)),
      "products" => array("type" => "multipleselect", "relation" => array("entity_name" => "Product", "where_array" => array("not_in_stock" => FALSE, "published" => TRUE), "search" => TRUE, "sort" => TRUE)),
      "products_boys" => array("type" => "multipleselect", "relation" => array("entity_name" => "Product", "where_array" => array("not_in_stock" => FALSE, "published" => TRUE), "search" => TRUE, "sort" => TRUE)),
      "products_girls" => array("type" => "multipleselect", "relation" => array("entity_name" => "Product", "where_array" => array("not_in_stock" => FALSE, "published" => TRUE), "search" => TRUE, "sort" => TRUE)));

  /** List params. */
  public $listParams = array("name", array("pregnancy_weeks" => "number"), "age_of_child", "sent_datetime", "update_frequency", array("countries" => "name"));

  /**
   * Create broadcast content
   * @param array $broadcast
   * @param array $user
   * @return array
   */
  public function createBroadcastContent($broadcast, $user) {

    $viewData = array();
    $viewData['subject'] = !empty($broadcast['subject']) ? $broadcast['subject'] : '';
    $viewData['email_appeal'] = !empty($broadcast['email_appeal']) ? $broadcast['email_appeal'] : '';
    $viewData['email_intro'] = !empty($broadcast['email_intro']) ? $broadcast['email_intro'] : '';
    $viewData['email_outro'] = !empty($broadcast['email_outro']) ? $broadcast['email_outro'] : '';
    $viewData['email_main_text'] = !empty($broadcast['email_main_text']) ? $broadcast['email_main_text'] : '';

    if(!empty($broadcast['article'])) {
      $viewData['email_main_text'] = $broadcast['article']['content'];
      if(strpos($broadcast['email_main_text'], '{PRODUCTS}') !== FALSE) {
        $viewData['email_main_text'] .= $broadcast['email_main_text'];
      }
    }
    //     if($user['country'] != 'UA') {
    //       $viewData['email_main_text'] = prepare_viewdata_not_ua($broadcast);
    //     }

    $ci = &get_instance();
    $ci->load->helper('project_broadcast');

    // Process products based on sex
    $products = array();
    $productAlias = 'products';
    if($user['child_sex'] == 'm' && isset($broadcast['products_boys']) && !empty($broadcast['products_boys'])) {
      $productAlias = 'products_boys';
    } elseif($user['child_sex'] == 'f' && isset($broadcast['products_girls']) && !empty($broadcast['products_girls'])) {
      $productAlias = 'products_girls';
    }
    if(isset($broadcast[$productAlias]) && !empty($broadcast[$productAlias])) {
      foreach ($broadcast[$productAlias] as $product) {
        $url = shop_url($product['page_url']);
        if (substr($url, -1) == '/') {
          $url = substr($url, 0 , -1);
        }
        $product['url_with_login_key'] = $url . '?' . LOGIN_KEY . '=' . $user['login_key'];
        $product['url_for_buy_button'] = $url . '?' . LOGIN_KEY . '=' . $user['login_key'] . '&' . REDIRECT_TO_CART_KEY . '=1';
        $products[] = $product;
      }
    }

    // Proccess data
    foreach ($viewData as &$data) {
      if (!empty($data)) {
        if(!empty($products)) {
          $data = ManagerHolder::get('ProductBroadcast')->process_product_broadcast_showcase($data, $products, $user);
        }

        // ------- Process $googleAnalData -------------------
        $googleAnalData = array('utm_source'   => '',
                                'utm_medium'   => 'email',
                                'utm_campaign' => 'UAM');
        if(!empty($broadcast['age_of_child'])) {
          $googleAnalData['utm_source'] = implode('_', explode(',', $broadcast['age_of_child'])) . '_week_baby_';
        }
        if(!empty($broadcast['pregnancy_weeks'])) {
          $weekNumbers = '';
          foreach ($broadcast['pregnancy_weeks'] as $pw) {
            $weekNumbers .= $pw['number'] . '_';
          }
          $googleAnalData['utm_source'] .= $weekNumbers . 'week_preg_';
        }
        $googleAnalData['utm_source'] = rtrim($googleAnalData['utm_source'], '_');
        // ----------------------------------------------------

        ManagerHolder::get('MandrillBroadcast')->addLoginKeyToLink($data, $user['login_key'], $googleAnalData);
        kprintfLettersContent($user, $data);
        // Search for short tag and replace it with link
        if (strpos($data, '{UNSUBSCRIBE_LINK}') !== FALSE) {
          $unsubscribeLink = site_url(USEFUL_TIPS_BROADCAST_UNSUBSCRIBE_PROCESS . '?' . LOGIN_KEY . '=' . $user['login_key']);
          $data = str_replace('{UNSUBSCRIBE_LINK}', $unsubscribeLink, $data);
        }
      }
    }

    return $viewData;
  }

  /**
   * PreProcessWhereQuery.
   * OVERRIDE THIS METHOD IN A SUBCLASS TO ADD joins and other stuff.
   * @param Doctrine_Query $query
   * @return Doctrine_Query
   */
  protected function preProcessWhereQuery($query, $pref, $what = "*") {
    $query = parent::preProcessWhereQuery($query, $pref, $what);
    if (strpos($what, 'products.') !== FALSE || $what == '*') {
      $query->addSelect("products_image.*")->leftJoin("products.image products_image");
    }
    if (strpos($what, 'products_boys.') !== FALSE || $what == '*') {
      $query->addSelect("products_boys_image.*")->leftJoin("products_boys.image products_boys_image");
    }
    if (strpos($what, 'products_girls.') !== FALSE || $what == '*') {
      $query->addSelect("products_girls_image.*")->leftJoin("products_girls.image products_girls_image");
    }
    return $query;
  }

}