<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UserSaleManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UserSaleManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("user_id", "sale_id");


  /** Fields. */
  public $fields = array("user" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "User")),
                         "sale" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Sale")));

  /** List params. */
  public $listParams = array("user.name", "sale.name");

}