<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * UserPregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class UserPregnancyWeekManager extends BaseManager {

  /** Fields. */
  public $fields = array("user" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "User")),
                         "pregnancy_week_id" => array("type" => "input_integer", "class" => "required", "relation" => array("entity_name" => "PregnancyWeek")));

  /** List params. */
  public $listParams = array("user.name", "pregnancy_week_id");

}