<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * WarehouseManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class WarehouseManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "name_ru" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "ref" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 50)),
                         "number" => array("type" => "input_integer"),
                         "city" => array("type" => "select", "relation" => array("entity_name" => "City")),
                         "type" => array("type" => "select", "relation" => array("entity_name" => "WarehouseType")));

  /** List params. */
  public $listParams = array("name", "number", "city.name", "type.name");

  /**
   * Sync
   */
  public function sync() {
    $CI = &get_instance();
    $CI->load->library('NewPostSdk');
    $CI->newpostsdk->setApiKey('eb5218a4df21f575da127c06afe055a7');


    $result = $CI->newpostsdk->getAllWarehouses();

    foreach ($result as $warehouse) {
      $entity = array();
      $entity['name'] = $warehouse->Description;
      $entity['name_ru'] = $warehouse->DescriptionRu;
      $entity['number'] = $warehouse->Number;

      $city = ManagerHolder::get('City')->getOneWhere(array('ref' => $warehouse->CityRef), 'e.*');
      $entity['city_id'] = $city['id'];

      $type = ManagerHolder::get('WarehouseType')->getOneWhere(array('ref' => $warehouse->TypeOfWarehouse), 'e.*');
      $entity['warehouse_type_id'] = $type['id'];

      $exists = ManagerHolder::get('Warehouse')->existsWhere(array('ref' => $warehouse->Ref));
      if ($exists) {
        ManagerHolder::get('Warehouse')->updateAllWhere(array('ref' => $warehouse->Ref), $entity);
      } else {
        $entity['ref'] = $warehouse->Ref;
        ManagerHolder::get('Warehouse')->insert($entity);
      }
    }
  }

}