<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastSegmentPregnancyWeekManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastSegmentPregnancyWeekManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("broadcast_segment_id", "pregnancyweek_id");


  /** Fields. */
  public $fields = array("broadcast_segment_id" => array("type" => "input_integer", "class" => "required"),
                         "pregnancyweek_id" => array("type" => "input_integer", "class" => "required"));

  /** List params. */
  public $listParams = array("broadcast_segment_id", "pregnancyweek_id");

}