<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastSegmentManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastSegmentManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "child_gender" => array("type" => "enum"),
                         "weeks" => array("type" => "multipleselect_chosen", "relation" => array("entity_name" => "PregnancyWeek", "name_field" => "number", "search" => TRUE)),
                         "ages" => array("type" => "multipleselect_chosen", "relation" => array("entity_name" => "AgeOfChild", "name_field" => "number", "search" => TRUE)),
                         "countries" => array("type" => "multipleselect_chosen", "relation" => array("entity_name" => "Country", "search" => TRUE)),
                         "broadcast_types" => array("type" => "array", "input-row-type" => "custom", "input-row-path" => "includes/admin/xbroadcast_segment/broadcast_types_array_row"),
                         "users" => array("type" => "include", "path" => "includes/admin/xbroadcast_segment/user_list"),
                         "last_login_filter" => array("type" => "include", "path" => "includes/admin/xbroadcast_segment/last_login_filter"),
                         "receipt_type_filter" => array("type" => "array", "input-row-type" => "custom", "input-row-path" => "includes/admin/xbroadcast_segment/receipt_type_filter_array_row"),
                         "open_type_filter" => array("type" => "array", "input-row-type" => "custom", "input-row-path"=> "includes/admin/xbroadcast_segment/open_type_filter"),
                         "page_visit_filter" => array("type" => "array", "input-row-type" => "custom", "input-row-path"=> "includes/admin/xbroadcast_segment/page_visit_filter")
  );

  /** List params. */
  public $listParams = array("name", "child_gender", array("weeks" => "number"), array("ages" => "number"), array("countries" => "name"));

  /**
   * PreProcessWhereQuery.
   * OVERRIDE THIS METHOD IN A SUBCLASS TO ADD joins and other stuff.
   * @param Doctrine_Query $query
   * @return Doctrine_Query
   */
  protected function preProcessWhereQuery($query, $pref, $what = "*")
  {
    $query = parent::preProcessWhereQuery($query, $pref, $what);
    if (strpos($what, 'users.') !== FALSE || $what == '*') {
      $query->addSelect("auth_info.*")->leftJoin("users.auth_info auth_info");
    }
    return $query;
  }

}