<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastManager extends BaseManager {

  const BROADCAST_CHANNEL_EMAIL = 'email';
  const BROADCAST_CHANNEL_FACEBOOK = 'facebook';

  /** Name field. */
  protected $nameField = "id";

  /** Order by */
  protected $orderBy = "created_at DESC";

  /** Fields. */
  public $fields = array("subject" => array("type" => "tinymce", "class" => "required", "attrs" => array("maxlength" => 65536)),
                         "variants_count" => array("type" => "input_integer", "class" => "required"),
                         "variants_stats_count" => array("type" => "tinymce", "attrs" => array("maxlength" => 65536)),
                         "is_single" => array("type" => "checkbox"),
                         "recipients_count" => array("type" => "input_integer", "class" => "required"),
                         "read_count" => array("type" => "input_integer"),
                         "link_visited_count" => array("type" => "input_integer"),
                         "successfully_sent_count" => array("type" => "input_integer"),
                         "unsubscribe_count" => array("type" => "input_integer"),
                         "converted_count" => array("type" => "input_integer"),
                         "sent_date" => array("type" => "datetime", "class" => "required"),
                         "template" => array("type" => "select", "relation" => array("entity_name" => "XBroadcastTemplate")),
                         "created_at" => array("type" => "datetime", "class" => "readonly", "attrs" => array("disabled" => "disabled")));

  /** List params. */
  public $listParams = array("sent_date", "template.type.name", array("template" => "name"), "variants_count", "is_single", "recipients_count", "successfully_sent_count", "read_count", "link_visited_count", "unsubscribe_count", "converted_count");

  /**
   * @return array|int
   * @throws ReflectionException
   */
  public function getPossibleBroadcastChannels()
  {
    $reflectedClass = new \ReflectionClass(__CLASS__);
    return array_filter($reflectedClass->getConstants(), function ($k) {
      return strpos($k, 'BROADCAST_CHANNEL_') === 0;
    }, ARRAY_FILTER_USE_KEY);
  }
}