<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastTemplateProductManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastTemplateProductManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("broadcast_template_id", "product_id");


  /** Fields. */
  public $fields = array("broadcast_template_id" => array("type" => "input_integer", "class" => "required"),
                         "product" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "Product")));

  /** List params. */
  public $listParams = array("broadcast_template_id", "product.name");

}