<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastSegmentUserManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastSegmentUserManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("broadcast_segment_id", "user_id");


  /** Fields. */
  public $fields = array("broadcast_segment" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "XBroadcastSegment")),
                         "user" => array("type" => "select", "class" => "required", "relation" => array("entity_name" => "User")));

  /** List params. */
  public $listParams = array("broadcast_segment.name", "user.name");

}