<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * XBroadcastSegmentAgeOfChildManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class XBroadcastSegmentAgeOfChildManager extends BaseManager {

  /** Primary Key Field. */
  protected $pk = array("broadcast_segment_id", "ageofchild_id");


  /** Fields. */
  public $fields = array("broadcast_segment_id" => array("type" => "input_integer", "class" => "required"),
                         "ageofchild_id" => array("type" => "input_integer", "class" => "required"));

  /** List params. */
  public $listParams = array("broadcast_segment_id", "ageofchild_id");

}