<?php  if(!defined("BASEPATH")) exit("No direct script access allowed");
/*
|--------------------------------------------------------------------------
| Admin base URL
|--------------------------------------------------------------------------
|
*/
$config["base_route"] = ADMIN_BASE_ROUTE;


/*
|--------------------------------------------------------------------------
| Admin menu items
|--------------------------------------------------------------------------
*/

$config["menu_items"] = array("admin" => array("admin",
																							 "adminlog"),
                              "articles_group" => array("article",
                                    										"articlecategory",
                                    										"articlecomment",
                                    										"author"),
                              "questions_group" => array("question",
      													                        "questioncomment"),
                              "pregnancyweek_group" => array("pregnancyarticle",
                                                             "pregnancyreview",
                                                             "pregnancyweek",
                                                             "articleexample"),
                              "shop_group" => array("showcase",
                                                    "product",
                                                    "productcomment",
                                                    "shopcomment",
                                                    "productparams",
                                                    "productcolor",
                              											"productbrand",
                              											"productcategory",
                              											"productcomment",
                              											"sale",
                                                    "productsalecategory",
                              											"siteorder",
                                                    "siteorderstatus",
                                                    "transaction",
                                                    "cart",
                                                    "productcategoryproductbrand",
                                                    "smstemplate",
                                                    "supplierrequest",
                                                    "supplierrequeststatus",
	                                                  "delivery"),
                              "shop_group_new" => array("parameter",
                                                        "parametervalue",
                                                        "filter",
                                                        "filtervalue"),
                              "user",
                              "page",
                              "team",
                              "settings",
                              "settingsgroup",
                              "defaultavatar",
                              "statistics" => array("conversion",
                                                    "conversionevent"),
                              "broadcast" => array("broadcast",
                                                   "broadcastrecipent",
                                                   "productbroadcast",
                                                   "recommendedproductsbroadcast",
                                                   "firstyearbroadcast",
                                                   "usefultipsbroadcast",
                                                   "returningbroadcast",
                                                   "tybroadcast",
                                                   "triggeredbroadcast",
                                                   "orderbroadcast",
                                                   "orderconfirmedbroadcast"),
                              "mandrillbroadcasts" => array("mandrillbroadcast",
                                                            "mandrillbroadcastrecipient",
                                                            "mandrillbroadcastopen",
                                                            "mandrillbroadcastvisitedlink"),
                              "form",
                              "newpost" => array("newpostaccount",
                                                 "city",
                                                 "counterparty",
                                                 "counterpartyaddress",
                                                 "counterpartycontactperson",
                                                 "warehouse",
                                                 "warehousetype"
                              ),
                              "campaign",
                              "remarketingcategory",
                              "template",
                              "storeinventory",
                              "store",
                              "xbroadcast_group" => array("xbroadcasttemplate",
                                                          "xbroadcastsegment",
                                                          "xbroadcast",
                                                          "xbroadcastrecipient",
                                                          "xbroadcasttype",
                                                          "xbroadcasttemplatesection",
                                                          "ageofchild"),
                              "facebookaudience",
                              "adminnotificationtemplate",
                              "taskschedule");
