<?php
/**
 * AdminLogManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class AdminLogManager extends BaseManager {

  /** Order by */
  protected $orderBy = 'created_at DESC';

  /** Fields. */
  public $fields = array("entity_name" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "entity_id" => array("type" => "input_integer"),
                         "description" => array("type" => "input", "attrs" => array("maxlength" => 255)),
                         "action" => array("type" => "enum"),
                         "admin" => array("type" => "select", "class" => "required"));

  /** List params. */
  public $listParams = array(array("admin" => "name"), "action", "entity_name", "entity_id", "description", "created_at");


  /**
   * Filter Values
   * @param string $filterName
   */
  public function getFilterValues($filterName) {
    if ($filterName == 'entity_name') {
      $files = scandir(APPPATH . 'controllers/admin');
      $xadmins = array();
      foreach($files as $filename) {
        if(preg_match("/^xadmin_(.*)\.php/", $filename, $matches)) {
          $xadmins[$matches[1]] = $matches[1];
        }
      }
      return $xadmins;
    } else {
      return parent::getFilterValues($filterName);
    }
  }


}