<?php
/**
 * BroadcastExcludeManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class BroadcastExcludeManager extends BaseManager {

  /** Fields. */
  public $fields = array();

  /** List params. */
  public $listParams = array("");

}