<?php
/**
 * BroadcastVisitedLinkManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class BroadcastVisitedLinkManager extends BaseManager {
  
  /** Throw exceptions */
  protected $throwExceptions = TRUE;

  /** Fields. */
  public $fields = array();

  /** List params. */
  public $listParams = array("");

}