<?php
/**
 * ConversionManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ConversionManager extends BaseManager {
  
  /** Cache key. */
//   public $CACHE_GROUP_KEY = 'ConversionCacheKey';
  
  /** Order By. */
  protected $orderBy = 'priority DESC';

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
  											 "internal_key" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)),
                         "description" => array("type" => "textarea"),
  											 "page" => array("type" => "input", "class" => "relUrl", "attrs" => array("maxlength" => 255)),
                         "priority" => array("type" => "input_integer"),
                         "has_page_table" => array("type" => "checkbox", "class" => "required"));

  /** List params. */
  public $listParams = array("name", "description", "priority", "has_page_table");

}