<?php
/**
 * ImageManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/common/ResourceManager.php';
class ImageManager extends ResourceManager {

  /**
   * PreDelete.
   * OVERRIDE THIS METHOD IN A SUBCLASS.
   * @param array $keyValueArray
   */
  protected function preDelete($keyValueArray) {
    $resources = $this->getAllWhere($keyValueArray, 'e.*');
    if ($resources) {
      foreach ($resources as $resource) {
        if(in_array($resource['web_path'], array('uploads/product/', 'uploads/parameter_group/'))) {
          continue;
        }
        if ($resource && file_exists($resource['file_path'] . $resource['file_name'])) {
          if (!@unlink($resource['file_path'] . $resource['file_name'])) {
            log_message('error', 'Could Not Delete: ' . $resource['file_path'] . $resource['file_name']);
          }
        }
        $thumbs[] = "_tiny";
        $thumbs[] = "_small";
        $thumbs[] = "_big";
        $thumbs[] = "_admin";
        foreach ($thumbs as $thumb) {
          $thumbPath = site_image_thumb_path($thumb, $resource);
          if (file_exists($thumbPath)) {
            @unlink($thumbPath);
          }
        }
      }
    }
  }

}