<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
/**
 * SettingsGroupManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class SettingsGroupManager extends BaseManager {

  /** Fields. */
  public $fields = array("name" => array("type" => "input", "class" => "required", "attrs" => array("maxlength" => 255)));

  /** List params. */
  public $listParams = array("name");

}